// <auto-generated />
using System;
using Desafio_Processo.API.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Desafio_Processo.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20230830183944_Produtos_Estoque")]
    partial class Produtos_Estoque
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.10");

            modelBuilder.Entity("Desafio_Processo.API.Models.Cadastros", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Grupo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT");

                    b.Property<string>("senha")
                        .HasColumnType("TEXT");

                    b.HasKey("Email");

                    b.ToTable("Cadastros");
                });

            modelBuilder.Entity("Desafio_Processo.API.Models.Produtos_em_Estoque", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeProduto")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Pr_Venda")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Quantidade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("codpro")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Produtos_em_Estoque");
                });
#pragma warning restore 612, 618
        }
    }
}
